# Generated by Django 4.1.1 on 2022-09-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SignUp", "0002_ilkmsuser_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="Ilkmsuser", old_name="gender", new_name="occupation",
        ),
        migrations.AddField(
            model_name="Ilkmsuser",
            name="user_type",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
