# Generated by Django 4.1.1 on 2022-09-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SignUp", "0003_delete_user_rename_gender_ilkmsuser_occupation_and_more"),
    ]

    operations = [
        # migrations.DeleteModel(name="User",),
    ]
