# Generated by Django 4.1.1 on 2022-09-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SignUp", "0004_delete_user"),
    ]

    operations = [
        # migrations.DeleteModel(name="User",),
        migrations.AlterField(
            model_name="Ilkmsuser",
            name="user_type",
            field=models.CharField(default="general_user", max_length=64, null=True),
        ),
    ]
