# Generated by Django 4.1.1 on 2022-09-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SignUp", "0005_delete_user_alter_ilkmsuser_user_type"),
    ]

    operations = [
        migrations.DeleteModel(name="IlkmsUser",),
    ]
