# Generated by Django 4.1.1 on 2022-09-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="chatbot_history",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("req", models.CharField(max_length=10000)),
                ("res", models.CharField(max_length=10000, null=True)),
            ],
            options={"db_table": "chatbot_history",},
        ),
    ]
